### ISSUE TITLE
VA command pod CoM needs adjusting.

### ISSUE THREAD

**Issue by Volkkeslate** [raidernick/KOSMOS#11]
The center of mass for the VA command pod needs to be moved more towards the bottom of the pod. Not only will this make it more in line with the stock pods, it should also stop the pod from trying to flip nose first into the airstream during reentry.

**Comment by Bezzier** [comment]
The VA command pod is really two pieces; a truncated conic pressure vessel, and a spherical dome heat shield. I'll do some math and figure the CoM of each, and then compute where it should be.  Great point.

**Comment by Bezzier** [comment]
Slightly more accurately the VA command pod can be treated as 5 parts:
1. hollow cylinder (top)
2. solid frustum of a right circular cone (hatch on top)
3. hollow frustum of a right circular cone (conic sides)
4. hollow oblate ellipsoid (lower shell and heat shield)
5. internals

I'm in the middle of calculating volumes, masses, and centers of mass for each of these, and will then be able to give a reasonable statement of where the CoM of the pod should be.

**Comment by Bezzier** [comment]
[Calc.xlsx](https://github.com/raidernick/KOSMOS/files/295816/Calc.xlsx)
OK, so... assuming 1" aluminum (2.7T/m3) for the pressure vessel parts of sections 3 and 4, an ablator density of .001T/Unit for the heat shield part of 4, section 1 to have a density of 1.5T/m3 (aluminum shell with some attachment points and insulation), a hatch approximation of for section 2 of 3" of solid aluminum, and uniform distribution of the internals, we get a CoM at -0.438182680414899 on the Y axis. @Volkkeslate, I will add that to the next pre-release build, if you could test it for me.

**Comment by Volkkeslate** [comment]
Downloaded and tested, it certainly feels a lot better now. Though the pod is still prone to flipping the wrong(read as Deadly) way around during reentry. Of course that's assuming you don't have your SAS on for whatever reason; running out of charge comes to mind?

This makes me think it may be something with the aerodynamics instead, but i know very little about how that's implemented in the game.

**Comment by Bezzier** [comment]
Why don't we try putting CoL at the bottom and see if that makes a
difference?

**Comment by Volkkeslate** [comment]
decided to do some digging through vanilla part configs. I 'borrowed' a couple of lines from the Mk.I command pod that seem to have fixed the issue.

CoPOffset = 0.0, 0.5, 0.0
CoLOffset = 0.0, -0.35, 0.0

these go in the node definitions section of the CFG.

while i was digging though i thought i'd do a little more tinkering and borrowed a couple of other lines for buoyancy. the pod also now floats a little more realistically (at least i think it does)  

CoPOffset = 0.0, 0.5, 0.0
CoLOffset = 0.0, -0.35, 0.0
CenterOfBuoyancy = 0.0, 0.5, 0.0
CenterOfDisplacement = 0.0, -0.3, 0.0
buoyancy = 1.5
buoyancyUseSine = False

so in the VA pod config the order is along the lines of:

// --- node definitions ---
// definition format is Position X, Position Y, Position Z, Up X, Up Y, Up Z

//VA original model nodes
//node_stack_bottom = 0, -0.7097499385, 0, 0, 1, 0, 2
//lower Point (parachute)
//node_stack_top00 = 0, 0.4883158785, 0, 0, 1, 0, 1
//upper (decoupler)
//node_stack_top02 = 0, 0.5859281, 0, 0, 1, 0, 1

node_stack_top00 = 0, 0.610394848125, 0, 0, 1, 0, 1 //Parachute point
node_stack_bottom = 0, -0.887187423125, 0, 0, -1, 0, 2 //Lockdown point
node_stack_top02 = 0, 0.732410125, 0, 0, 1, 0, 1 //VA RCS tower point

CoPOffset = 0.0, 0.5, 0.0
CoLOffset = 0.0, -0.35, 0.0
CenterOfBuoyancy = 0.0, 0.5, 0.0
CenterOfDisplacement = 0.0, -0.3, 0.0
buoyancy = 1.5
buoyancyUseSine = False

Buoyancy could be decreased slightly if it feels too floaty. The Mk 1-2 pod has a buoyancy value of 1.1.

**Comment by Bezzier** [comment]
V, if you're happy with those values working, you can make a PR and I'll
pull it. I have to admit I have been stuck dealing with other things for
the last two weeks.

Are you happy with the rest of the changes? Do they work for you? Remember
this isn't the only bite at the apple. We can keep tinkering.

**Comment by Volkkeslate** [comment]
yeah this is looking fixed and functioning nicely now. Still tinkering with the other parts but for the most part nothing springs to mind at present.

Edit: i actually have no clue how to work the Pull Request system, reading up on it now.

**Comment by Volkkeslate** [comment]
pardon my mess, this was my first attempt using this convoluted pull request system

**Comment by Bezzier** [comment]
Don't worry! It takes us all time to learn!

**Comment by Bezzier** [comment]
closed as fixed by #13
