### ISSUE TITLE
Manufacturer tab

### ISSUE THREAD

**Issue by Volkkeslate** [raidernick/KOSMOS#12]
while not a pressing issue, adding the parts under their own manufacturer tab in the VAB would be nice. Consider this one more of a wishlist than anything.

**Comment by Bezzier** [comment]
Not sure what is meant here? I don't think I've ever seen that... I always leave things sorted by category. How can I see something sorted by manufacturer?

**Comment by raidernick** [comment]
you need to add an agency to the parts

**Comment by Bezzier** [comment]
OK, thanks.

**Comment by Bezzier** [comment]
I believe this can be closed now, with the agency added for 0.16.0
