### ISSUE TITLE
APAS-69 Docking Node Size

### ISSUE THREAD

**Issue by Bezzier** [raidernick/KOSMOS#2]
Currently this uses size 1 and is dockable with clamp-o-trons. APAS-69 should only dock to other APAS-style systems. Suggest a new node definition.

It's possible that Tantares or other mods may have a standard APAS node size defined.  If so, it might additionally be possible to generate a module manager file to ensure compatibility.

**Comment by raidernick** [comment]
make a pr for the fix then

**Comment by Bezzier** [comment]
Addressed in Pull Request #8 along with other fixes
