### ISSUE TITLE
Fuel line and strut fail to load

### ISSUE THREAD

**Issue by Volkkeslate** [raidernick/KOSMOS#20]
Both parts need a rewrite to follow new syntax/formatting for their type of part. (Compound part)

![error](https://cloud.githubusercontent.com/assets/10903349/19407204/11d528e8-9260-11e6-80d7-f8725850966f.png)

**Comment by Bezzier** [comment]
@Volkkeslate does the fix on your fork work for this, or does anything need to be changed in it?

**Comment by Volkkeslate** [comment]
@Bezzier it does work, i just wasn't sure if my fork was up to date with this version due to the weird way that github works. I need to get the strut working before i'll submit a pull request.

**Comment by Volkkeslate** [comment]
both parts are fixed in my branch, it's still behind this one though since i can't figure out how github's backwards system works :D

**Comment by raidernick** [comment]
in the git console do a "git pull" on the KOSMOS/master branch, then switch to your repo and do a "git merge" with the master you just pulled. Then do a "git sync". Then add your changes to your branch and make a PR here and I'll merge it.

**Comment by Bezzier** [comment]
Well, that worked!
